# "~MD013/line-length"
# "~MD025/single-title/single-h1"
# "~MD036/no-emphasis-as-heading"
# "~MD033/no-inline-html"
# "~MD049/emphasis-style"
# "~MD012/no-multiple-blank"
# "~MD024/no-duplicate-heading/no-duplicate-header"
# "~MD001/heading-increment/header-increment"

rules ~MD013, ~MD025, ~MD036, ~MD033, ~MD049, ~MD012, ~MD024, ~MD001
