rules "~MD013/line-length"
rules "~MD025/single-title/single-h1"
rules "~MD036/no-emphasis-as-heading"
rules "~MD033/no-inline-html"
rules "~MD049/emphasis-style"
rules "~MD012/no-multiple-blank"
rules "~MD024/no-duplicate-heading/no-duplicate-header"

rules "~MD001/heading-increment/header-increment"
