# Default state for all rules
default: true
# "~MD013/line-length"
MD013: false
# "~MD025/single-title/single-h1"
MD025: false
# "~MD036/no-emphasis-as-heading"
MD036: false
# "~MD033/no-inline-html"
MD033: false
# "~MD049/emphasis-style"
MD049: false
# "~MD012/no-multiple-blank"
MD012: false
# "~MD024/no-duplicate-heading/no-duplicate-header"
MD024: false
# "~MD001/heading-increment/header-increment"
MD001: false
