name: GitHub Actions
on: [push, pull_request]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      # Run markdownlint
      # From https://github.com/marketplace/actions/markdownlint-cli
      - name: Run markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          dot: true
          config_file: .markdownlint.yaml
          ignore_files: google-doc.md
        #   rules: markdownlint-custom.js
        #   ignore_files: examples/ignore/*
        #   ignore_path: examples/.markdownlintignore
